terraform {
  required_version = ">= 0.14"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.30.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "2.1.0"
    }
  }
}


# Create remote backend if required
resource "aws_s3_bucket" "tf_backend" {
  bucket_prefix = "tf-backend-"
  force_destroy = true
  count         = var.remote_backend ? 1 : 0

  tags = local.tags
}


resource "local_file" "backend" {
  filename        = "backend.tf"
  file_permission = "0644"
  count           = var.remote_backend ? 1 : 0

  content = <<-EOF
  # Don't edit this file. Generated by terraform
  terraform {
    backend "s3" {
      region = "${var.aws_region}"
      bucket = "${aws_s3_bucket.tf_backend[count.index].bucket}"
      key    = "${var.project}.tfstate"
    }
  }
  EOF
}
