variable "tags" {}
variable "instance_image_id" {}
variable "key_name" {}
variable "worker_instance_type" {}
variable "worker_count" {}
variable "worker_pool_subnet_id" {}
variable "worker_vpc_security_group_ids" {}
variable "private_key_path" {}
variable "master_private_ip" {}
variable "bootstrap_token" {}
variable "iam_profile_name" {}
