variable "tags" {}
variable "kubeconfig_path" {}
variable "instance_image_id" {}
variable "key_name" {}
variable "master_instance_type" {}
variable "master_subnet_id" {}
variable "master_vpc_security_group_ids" {}
variable "private_key_path" {}
variable "iam_profile_name" {}
